### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by tslater** [tumblr/jetpants#22]
I see lots of stars, but almost no issues. The commits also dropped off sharply...

**Comment by dallasmarlow** [comment]
@tslater yes, internal development is done on a internal git repo and then pushed as release candidate branches (like the one currently opened 4 days ago which contains roughly 100 commits).

**Comment by eelias** [comment]
From what I understand, Tumblr has more people working on this project now than at any point in the past :)

That said, it would be certainly be nice if the internal repo could be pushed to github more often. The current setup makes it difficult for potential external users/contributors, since we may be branching off of stale code, unknowingly introducing merge conflicts, etc.

**Comment by KirilAngov** [comment]
Yes, we are very much dedicated to Jetpants development as Dallas and Evan pointed out. We do have internal jetpants plugins for all of our custom logic but we make every effort to keep the core fully working and usable by other companies/individuals.

We definitely should be releasing new versions much more often.
